version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@angular/language-service"
    versions:
    - 11.2.1
    - 11.2.10
    - 11.2.2
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/cli"
    versions:
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@ionic/angular"
    versions:
    - 5.5.5
    - 5.6.0
    - 5.6.1
    - 5.6.2
    - 5.6.3
    - 5.6.4
  - dependency-name: "@ionic-native/splash-screen"
    versions:
    - 5.32.0
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.4
    - 3.6.6
    - 3.6.7
    - 3.6.9
  - dependency-name: karma
    versions:
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: jasmine-core
    versions:
    - 3.6.0
    - 3.7.0
  - dependency-name: "@ionic/storage"
    versions:
    - 3.0.2
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
  - dependency-name: "@ionic-native/status-bar"
    versions:
    - 5.31.1
  - dependency-name: "@ionic-native/core"
    versions:
    - 5.31.1
  - dependency-name: rxjs
    versions:
    - 6.6.3
  - dependency-name: karma-jasmine
    versions:
    - 4.0.1
